### ISSUE TITLE
请求合作。嗯~ o(*￣▽￣*)o

### ISSUE THREAD

**Issue by ScSofts** [maomao1996/react-music#11]
我正在使用React写一个类似的播放器。使用Material-UI。希望你能和我合作。欢迎加入组织：[https://github.com/Sc-Softs/CloudMusic](https://github.com/Sc-Softs/CloudMusic) PS:我们是同志了

**Comment by ScSofts** [comment]
后端由我来写。我准备实现Node.js PHP C++ & libuv 3个版本的API

**Comment by ScSofts** [comment]
还有，我非常讨厌Vue.

**Comment by maomao1996** [comment]
不好意思啊，最近忙没精力搞这些个人项目了 😵

**Comment by ScSofts** [comment]
好的。不打扰了。
